### ISSUE TITLE
[FEATURE] Study the updates in revision 5 of NIST 800-53

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#106]
**Is your feature request related to a problem? Please describe.**
How do the updates and additional controls of the latest NIST 800-53 set impact OpenRMF.

**Describe the solution you'd like**
See what controls we need to add or update, the mapping of VULNID to CCI to CONTROL, etc.

**Additional context**
https://www.securityweek.com/nist-updates-flagship-sp-800-53-security-and-privacy-controls

Final Draft out now, comments due mid-May 2020.

**Comment by DaleBinghamSoteriaSoft** [comment]
done.
