### ISSUE TITLE
[FEATURE] Add ability to add benchmarks and STIGs not available to the public.

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-docs#108]
Add the ability to add benchmarks and STIG Checklists not available to the general public.

**Describe the solution you'd like**
The ability to upload STIG benchmarks separately from the pre-loaded data.  I would like to load the 24Jan2020 release of WIndows 2016 Server (V1R12) into the RMF tool so the scan data.  These may not be publicly available yet, but is current for Gov systems.

We are currently working on a new set of 2016 servers and downloaded the latest benchmark and STIGs from DISA.   I have loaded the benchmark into the SCAP scanner tool and produced the results file.  If I upload this XCCDF into OpenRMF, it compares against benchmark V1R9, which includes 88 N/R items.  Most of these are not actually tested in the latest benchmark or are obsolete.    

This is also true for 2012 R2 servers that have a January 2020 update to V2R18 and importing the SCAP results compares against V2R17.  

**Describe alternatives you've considered**
Open the DISA Stig Viewer, create a checklist (or open a pre-filled template) with the current STIG baseline, and import the XCCDF into the file, save and then import it into OpenRMF.  

**Additional context**

**Comment by Cingulara** [comment]
The public STIG available for STIGs https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_MS_Windows_Server_2016_V1R10_STIG.zip is this one.  That is for the STIG. 

https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_MS_Windows_Server_2016_V1R12_STIG_SCAP_1-2_Benchmark.zip this is the SCAP Benchmark which is V1R12. 

The STIG and Benchmark may not necessarily be the same as @degthat8412 keeps telling me. 

The Templates API pre-loads the XCCDF manual STIG templates, not the benchmark for SCAP scanning, and right now we are at https://github.com/Cingulara/openrmf-api-template/blob/develop/src/templatefiles/U_MS_Windows_Server_2016_STIG_V1R9_Manual-xccdf.xml. I will be added in the newer public ones as we go forward. 

The idea of this is a good one. It may be a little bit before we add it in. It will stay here to reference though. 

You could pull the code down, add the manual XCCDF STIG yourself, and rebuild for sure if you need it right now.

**Comment by Cingulara** [comment]
Nothing this separately again:  benchmark = SCAP, manual XCCDF = Checklist for OpenRMF. We match these and match the SCAP to the manual XCCDF when you upload the SCAP versus a checklist. That is how we manage these. 

I do need to put the latest manual XCCDF into the template API files.

**Comment by Cingulara** [comment]
The OpenRMF Professional version https://www.soteriasoft.com/ has a way to add a new DISA checklist template (xxxxxxx-Manual-XCCDF.xml file) as a new public template for all. And this includes PKI enabled checklist templates from DISA that are not publicly available. That works now. 

This will be included in a future OSS version.

**Comment by Cingulara** [comment]
We include the latest DISA STIGs in updates within our Template API component. We just did that now.
