### ISSUE TITLE
add a "test" YML to spin up the "latest" version of openRMF versus a named image

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openrmf-docs#14]
Make a "stop.sh" and "start.sh" for the test version of openRMF for people to test :latest

- make sure it pulls the latest images first
- make sure it runs the latest images
- make it point to a dev area for MongDB
- make it run on different ports
- make the NATS service listen on a test instance (env variables injected here for features)

**Comment by Cingulara** [comment]
done in 0.6.1.
