### ISSUE TITLE
[BUG] Incorrect Port In setup-realm-linux.sh

### ISSUE THREAD

**Issue by medined** [Cingulara/openrmf-docs#157]
**Describe the bug**
The setup-realm-linux.sh script uses docker exec to run programs inside the keycloak container. Since the command is being run inside the container, the published port does not matter. The port should be 8080 instead of 9001.

**To Reproduce**

When running the "Authenticating to Keycloak Master Realm" step, the connection is refused.

**Expected behavior**

The credential configuration should happen.

**Desktop (please complete the following information):**

I am using Ubuntu.

**Additional context**

The "first OpenRMF admin account" should not be 'admin' since that is the default administrator account. It should be something like 'rmf-admin' or 'john' to avoid confusion with the original keycloak admin user.

Thanks for making this software available.

**Comment by Cingulara** [comment]
We chose 9001 so the OpenRMF on port 8080 could run on the same box as Keycloak on a separate port. We chose 9001 randomly.  We have a related issue  in https://github.com/Cingulara/openrmf-web/issues/156 to make that port a choice when running all on one machine. 

If in K8s this issue goes away with service and ingress mapping.

**Comment by Cingulara** [comment]
And I believe the script sets the first admin to whatever you type in. The line 60 starts that section. And it is set when you enter the name around line 5. We edited the prompts recently in /develop to make them a little easier to understand what you needed to do.

https://github.com/Cingulara/openrmf-docs/blob/develop/scripts/keycloak/setup-realm-linux.sh

**Comment by medined** [comment]
Please see PR#1. This issue relates to line 15 where the port is hard-coded to 9001. If you set an ENV variable to the port being used in the docker-compose yaml file. Then that ENV variable can be used in this command. You'd need to escape the "$" character. 

Regarding the OpenRMF administrator account. I did add some context to the prompt. I won't be insulted if you don't use my suggestion.

**Comment by Cingulara** [comment]
The auth.js file in the web UI also has to point to this. https://github.com/Cingulara/openrmf-web/blob/develop/js/auth.js So we cannot just change the Keycloak setup. We need to point what goes to it. Or architect it in a way that is easier to customize.

**Comment by medined** [comment]
Yes. That container would also need the ENV variable passed into it. Pointing out the obvious, using ENV variables shows dependencies between containers and makes them less brittle.

**Comment by Cingulara** [comment]
That container uses NGINX and static HTML files. At least it does right now.

**Comment by Cingulara** [comment]
The port is correct and the Linux and Mac Realm SH files are correct. This dealt with a firewall port restriction. We updated documentation to make sure we stated that out loud up front.
