### ISSUE TITLE
[BUG] Use HEREDOC in setup-realm-linux.sh

### ISSUE THREAD

**Issue by medined** [Cingulara/openrmf-docs#158]
**Describe the bug**

When running setup-realm-linux.sh, I see this error:

./setup-realm-linux.sh: line 76: warning: here-document at line 75 delimited by end-of-file (wanted `echo')

**Expected behavior**

The script to run without errors.

**Desktop (please complete the following information):**

I am using ubuntu 20.04.

**Additional context**

The following syntax seems to work:

   sudo docker exec -i $keycontainer /opt/jboss/keycloak/bin/kcadm.sh update realms/openrmf -f - <<EOF
{"defaultRoles" :["offline_access", "uma_authorization", "Reader"]}
EOF

**Comment by Cingulara** [comment]
Yes that ending has bugged us for a bit but we had not tackled it yet. Thank you. I will do this with the other script edit when we update Keycloak to a recent version.

**Comment by medined** [comment]
Please see PR#1.
