### ISSUE TITLE
[BUG] When re-running setup-realm-linux.sh, cid variable is not set.

### ISSUE THREAD

**Issue by medined** [Cingulara/openrmf-docs#159]
**Describe the bug**

When re-running the script (after using docker-compose down and running the start.sh script again), the client is already created so the cid variable is not set. This means the create protocol mapper section does not work.

**To Reproduce**

```
./start.sh
./setup-realm-linux.sh
docker-compose down
./start.sh
./setup-realm-linux.sh
```

**Expected behavior**

The script to run cleanly.

**Desktop (please complete the following information):**

ubuntu 20.04

I solve this type of issue using `jq` like this:

```
    cid=$(sudo docker exec -i $keycontainer /opt/jboss/keycloak/bin/kcadm.sh get clients -r openrmf -q clientId=openrmf 2>/dev/null | jq --raw-output '.[0].id'
    if [ -z $cid ]; then
      cid=$(sudo docker exec -i $keycontainer /opt/jboss/keycloak/bin/kcadm.sh create clients -r openrmf -s enabled=true -s clientId=openrmf -s publicClient=true -s 'description=openrmf login for Web and APIs' -s 'redirectUris=["http://'$keyip':8080/*"]' -s 'webOrigins=["*"]' -i)
    fi
    echo "$cid"
```

**Comment by Cingulara** [comment]
We are WAYYYY over due for a Keycloak upgrade. So when I do that I will check into this and test it. Thank you for the fix. 

Or if you wish, do a fork, fix it, and do a PR back if you have the time.

**Comment by medined** [comment]
Please see PR#1.
