### ISSUE TITLE
[BUG] When I first log into OpenRMF, it says "Verify API's authentication settings".

### ISSUE THREAD

**Issue by medined** [Cingulara/openrmf-docs#160]
**Describe the bug**

I followed the step-by-step instructions at https://github.com/Cingulara/openrmf-docs/blob/master/step-by-step.md. When I log into OpenRMF it shows the following message:

> There is an Authentication problem. Please logout and log back in. And have the application administrator verify your API's authentication settings.

**Expected behavior**

I expected the Dashboard to display without errors.

**Screenshots**

![openrmf-api-error](https://user-images.githubusercontent.com/43589/84567859-9a3b0b00-ad49-11ea-9c03-eea671f8e4b3.png)

**Desktop (please complete the following information):**

Ubuntu 20.04

**Comment by medined** [comment]
Could this issue be related to my using localhost despite the instructions that say: "Make sure you DO NOT use http://localhost/ as "localhost" means something specific with Docker images. "?

**Comment by Cingulara** [comment]
This means the setup may have been done with missing a step (not editing the .env file, not setting up Keycloak right, etc.) or how you reference the application. And yes, you cannot use "localhost" as using "localhost" in reference to a docker container means itself. You have to use the IP or the name of the machine running the OpenRMF stack.   You have to use http://some.ip.address:8080/ or its name.

**Comment by Cingulara** [comment]
@medined  Please suggest a better error message as well. What would make sense here so we can make sure we say it?

**Comment by medined** [comment]
I'm working on a laptop. Should I be using 127.0.0.1 instead of localhost? Should I be creating an entry "openrmf" in /etc/hosts pointed to 127.0.0.1? Networking is not a strength for me. When I inspect the openrmf-web image, I see it has an empty NetworkSettings.IPAddress which I did not expect.

**Comment by Cingulara** [comment]
No, 127 is basically the same as localhost. @degthat8412 may be able to help here. 

If your laptop is hooked to a wired or wireless network, and it has an IP address, us that IP address of your main laptop. I think `ifconfig` works on Linux based systems. Use that IP. 

for example, if I find my laptop is running 10.10.3.12 I would use http://10.10.3.12:8080/ and get to it that way.

**Comment by medined** [comment]
I just learned that `eth0` is no longer used. The new interface name is `wlp4s0`. The IP address can be found, on my sytem, using `ip -4 addr`. Also logically, my local network uses 198.168.1.X so that should have been a clue.

I will bring everything down and retry. Thanks for your quick responses.

**Comment by medined** [comment]
The keycloak setup only seems to work when I use "localhost" as the response to ./setup-realm-linux.sh script. I thought that it might be JWT-AUTHORITY that causes my issue. So I added openrmf as an alias for 192.168.1.21 in /etc/hosts. But that results in this:

![invalid-parameter](https://user-images.githubusercontent.com/43589/84571836-04f94000-ad64-11ea-889d-ff9163e9e97c.png)

Interesting that I did not run into this issue before.

For completeness, here is the offending URL:

http://openrmf:9001/auth/realms/openrmf/protocol/openid-connect/auth?client_id=openrmf&redirect_uri=http%3A%2F%2Fopenrmf%3A8080%2F&state=554cec7b-bda0-4690-8469-8e94b9197001&response_mode=fragment&response_type=code&scope=openid&nonce=d34cc148-805f-4ba1-8fe5-c92c85585416

**Comment by Cingulara** [comment]
You cannot use localhost in the .env or in going to :8080 at all. That is why that script says "go to http://{ip-address}:8080/. 

The .env file needs to point to an IP.
Your browser to load this has to point to the IP. 
The IP has to be setup in keycloak as the Valid URI as well. Make sure of that. 

![image](https://user-images.githubusercontent.com/46137145/84571951-d465d600-ad64-11ea-996d-585358f6b584.png)

**Comment by medined** [comment]
Thank you for your patience with me. I really want to get OpenRMF working. I created a project - https://github.com/medined/openrmf-at-aws - in order to codify what I have been doing. It's repeatable now.

The project uses Terraform and Ansible to:
* start an instance with ports 8080, 9001, and 22 open.
* install the two zip files from the OpenRMF release page.
* Run start.sh and setup-realm-linux.sh

This all works fine so far. And I use the IP address of the keycloak container during the setup-realm-linux script, so now I understand that better. And it's using port 8080.

I can visit the keycloak page, then click on Administration Console. This results in "HTTPS Required."

I'd understand if I'm asking for too much support. Just let me know.

**Comment by Cingulara** [comment]
So this original bug is basically something to do with the ports being required for 8080 and 9001 with any firewall or SELinux setup someone may have on Linux, Mac, or Windows. So that is answered. It was not a bug but we need to update docs on settings required.

As for the new question, we have a setup in EKS linked in our deployment area here in this Repo. Or you can also use ECS and ECR for containers with EC2 or Fargate I believe. If you want to use the containers as is. FYI I am testing "rootless" containers now across all the pieces so they are in a more secure fashion. That should be out in the next couple of weeks. 

If you want to just use EC2 then I am not sure as of yet. I have not tried it like that. I know one friend of mine at AWS said with at least ECS you will need app load balancers I believe to make it point to the URLs correctly. We have EKS setup with ingress to map HTTPS using our ACM cert to the internal HTTP and that service maps to the container. 

This question and investigation may be easier in Slack https://join.slack.com/t/openrmftool/shared_invite/zt-ck8lqld0-8LD7k66mzj7WsIno9YFrMg so any one from the community we are building there can also chime in if possible.

**Comment by Cingulara** [comment]
FYI information updated on the ports and firewall information here: https://github.com/Cingulara/openrmf-docs/blob/develop/step-by-step.md

**Comment by medined** [comment]
Thank you for the help. The end result is a 100% automated provision for an AWS instance at https://github.com/medined/openrmf-at-aws using Terraform and Ansible.
