### ISSUE TITLE
[FEATURE] Implement a NATS server cluster

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#17]
Can use in docker-compose as a test

Need to use the CRD in k8s for NATS as well as OpenShift

**Comment by DaleBingham** [comment]
Possibly look at NATS streaming versus NATS as well.

**Comment by Cingulara** [comment]
https://docs.nats.io/nats-on-kubernetes/nats-kubernetes

**Comment by Cingulara** [comment]
For what we have on demo, not needed really. The single one works fine. We can use the https://raw.githubusercontent.com/nats-io/k8s/master/nats-server/single-server-nats.yml setup instead of what we have now.
