### ISSUE TITLE
Import of multiple Nessus files

### ISSUE THREAD

**Issue by cbg-teamomni** [Cingulara/openrmf-docs#171]
Currently you can upload multiple checklists in batches of 10. There is also a need to upload multiple Nessus scans because a complex system may have multiple scans based on the combined technologies involved.

**Comment by Cingulara** [comment]
Yes we have talked about this and it is in our backlog of ideas. Right now the Nessus file upload just overwrites the previous one, if any, and all reports are only on that one .nessus file. We need to allow multiple and allow updates / merges / etc. eventually.

**Comment by Cingulara** [comment]
This is now done in the Professional version @cbg-teamomni at https://www.soteriasoft.com/products/openrmf-professional.html
