### ISSUE TITLE
[FEATURE] Display the IP address, with xxx.xxx in the first 2 octets for security, on the Checklist viewing page

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#187]
**Is your feature request related to a problem? Please describe.**
Where the individual checklist page has the FQDN, type, hostname, etc. put the IP Address from the checklists as well. But hide the first two octets. 

**Describe alternatives you've considered**
* Do not show it, but that does not work. 
* Show the whole thing, but not w/ the hostname as well

**Additional context**
We hide the first two octets in the Nessus reporting page. Do something similar here w/ the IP address data.

**Comment by EngThis** [comment]
Thats not neccessary, you shouldnt be viewing your checklists on a system below the security rating of the system scanned therefore no need to obfuscate the first two octets...

**Comment by DaleBinghamSoteriaSoft** [comment]
Going to leave this as is unless someone comes along and requests it.
