### ISSUE TITLE
[FEATURE] Automated A&A artifact maintainer capability 

### ISSUE THREAD

**Issue by CODEHUSTLE** [Cingulara/openrmf-docs#191]
**Why:**
A&A package artifacts that prove particularly difficult to maintain (and keep synchronization between) include the Ports, Protocols and Services Matrix (PPSM), hardware list, software list, and system diagrams (e.g., system authorization boundary, system enterprise and information security architecture, information flow).  A change in any of these artifacts may generate a need to update one-or-more of the others.  The management and maintenance of these separate artifacts can be labor-intensive, time-consuming, and prone to error.  Different applications are used to separately maintain each of these artifacts (e.g., Word, Visio, Excel).  An effective solution would accelerate and enhance the RMF authorization process for Navy systems, speeding the deployment of new capabilities, reducing the cost of design and sustainment, and providing design clarity that will improve the quality of risk acceptance decisions by AOs.

**Requirement description:**
An automation-assisted method of maintaining the Ports, Protocols and Services Matrix (PPSM), hardware list, software list, and system diagrams (e.g., system authorization boundary, system enterprise and information security architecture, information flow).  Values for hostnames, IP’s, ports, etc., should not be able to fall out of sync.

**Comment by Cingulara** [comment]
The checklists, nessus patch vulnerabilities, patch score history, checklist score history, automated PPSM, hardware list, and software list is in the OpenRMF Professional v2.2 release! https://www.soteriasoft.com/ has more information on that. It also lets you check IN or OUT boundary crossing as well.
