### ISSUE TITLE
[FEATURE] Color indicators for artifact components

### ISSUE THREAD

**Issue by CODEHUSTLE** [Cingulara/openrmf-docs#192]
**Why:**
Not only useful for the A&A process, but also the ISSO/ISSM continuous monitoring and fix prioritization activities.  A relatively low severity vulnerability in a more exposed position may warrant a higher fix priority than more protected component with a higher severity vulnerability.  This functionality would make those prioritization decisions easier, and help with overall vulnerability management oversight.

**Requirement description:**
Integrating color coding or other visual means of quickly identifying (by severity, age, and residual risk) those components in an artifact that are affected by vulnerabilities tracked in OpenRMF.

**Comment by Cingulara** [comment]
This deals with the raw severity, set severity, likelihood, impact, and other information that is in the POAM to set this.

**Comment by Cingulara** [comment]
This is done in the POAM for OpenRMF Professional and will stay there really. There is also a POAM cube report, export, and API to use.

You can do this in the XLSX POAM export by specifying the fields as well.
