### ISSUE TITLE
[FEATURE] Enterprise Search

### ISSUE THREAD

**Issue by CODEHUSTLE** [Cingulara/openrmf-docs#196]
Currently you are unable to search across checklists for keywords/phrases.

You could implement single checklist search alongside the filter by searching the loaded sessionStorage data which contains all vulnerabilities for current loaded checklist. An enterprise search would be a better solution, but would be a larger level of effort to implement.

**Comment by Cingulara** [comment]
This could be a search for "contains" in checklists for a system package by looking in the report database and using MongoDB for a keyword or phrase search.  This would be a "table scan" type of search unfortunately but it could work here.

**Comment by Cingulara** [comment]
This is scheduled to go into the Professional version. https://www.soteriasoft.com/products/openrmf-professional.html
