### ISSUE TITLE
[FEATURE] Implement CI/CD with GitHub Actions and Unit Tests, SonarQube, etc.

### ISSUE THREAD

**Issue by DaleBingham** [Cingulara/openrmf-docs#20]
* we need to fix Unit Tests
* we need to get SonarQube SaaS working for this project
* we need to automate /develop and /release and /master pushes to scan and run through correctly to include building

**Comment by Cingulara** [comment]
I have this building and testing for .NET Core 2.2. We also should setup and add in the SonarSource work: https://github.com/SonarSource/sonarcloud-github-action

**Comment by Cingulara** [comment]
Once that is done on all repos, and we fix the tests, this can be done and we move on.

**Comment by Cingulara** [comment]
Had to do a few things for this to work right:
- make the .github/ folder in develop and release branches
- get the dotnet core YML file for testing correct
- do PR's for develop to release to master
- Add the badge on the README.md file to show its status
- Remove 'include admins' on the release and master branch rules just in case there is a conflict on merging

**Comment by Cingulara** [comment]
I have this on the ext score API and the score msg repos. I need to do it on the rest of them minus the web one.
