### ISSUE TITLE
SSL Required After Install

### ISSUE THREAD

**Issue by crl0901** [Cingulara/openrmf-docs#209]
If this has already been addressed, I apologize.  I searched all issues and didn't see it mentioned.

I followed the step-by-step instructions here: https://github.com/Cingulara/openrmf-docs/blob/master/step-by-step.md
I'm running this on RHEL7.9.
After running the start.sh and setup-realm-linux.sh scripts, I go to log in to the admin console and get the following error:
![image](https://user-images.githubusercontent.com/12235594/104476345-25091000-558e-11eb-8ca0-2103732209c4.png)

I tried manually running the disable SSL command from the realm script to no avail.  I'm accessing the Keycloak interface using the server's IP address at port 9001.  I don't see any errors during the install, everything seems to run correctly.  What am I missing here?  i

**Comment by Cingulara** [comment]
@crl0901 can you go to the http://xxx.xxx.xxx.xxx:9001/auth/ and login with the "admin" login for Keycloak? Then go to the OpenRMF realm if it is not shown under the top left Keycloak icon. If it says "master" move your mouse over there and a menu pops down to let you select it. Then go to the Realm Settings and then the Login tab like the picture below. Make sure the "Require SSL" is setup to "none" like this below. If your Keycloak is set to http and your access to your OpenRMF setup is also http, this should work. 

Also make sure your .env file you edited to make the IPs match how you access OpenRMF also is http for the setup. Use the IP address : 9001 as below.

```
JWT-AUTHORITY=http://xxx.xxx.xx.118:9001/auth/realms/openrmf
JWT-CLIENT=openrmf
```

![image](https://user-images.githubusercontent.com/46137145/104660710-12c5c980-5695-11eb-8d5d-957bb61bed27.png)

**Comment by crl0901** [comment]
I can reach http://xxx.xxx.xxx.xxx:9001/auth/, I click 'Administration Console' to log in, and that's when I get redirected to that error.

This is a brand new install with the latest installation scripts.

**Comment by Cingulara** [comment]
So going straight to http:// :9001/auth gives you that? I just ran this whole install from scratch on my macbook and I can get into Keycloak 100%. If you can run ` docker volume ls ` and look for a volume that has "-keycloak-postgres" at the end. Bring down keycloak and the OpenRMF stacks, and then run ` docker volume rm xxxxxx ` where xxxxx is the name of that volume. That is where the DB stores its data. Then bring back up just the Keycloak stack by itself. It should make a new Keycloak setup and install but it may take 2 - 4 minutes depending on the speed of your box.

When you let that sit a few minutes, then go back to http://xxx.xxx.xxx.xxx:9001/auth/ and see if you can log in with admin/admin. This assumes you use the Keycloak "start.sh" type script and you do not modify the docker-compose.yml file for Keycloak. 

See if that can at least get you into Keycloak. There is nothing in the setup forcing SSL in the docker setup of Keycloak that is done for OpenRMF. You have to specifically specify SSL in a bunch of places for that to work.

**Comment by Cingulara** [comment]
@crl0901 did you try to shut down all docker stacks, remove the Keycloak volume, and then spin this back up, let it sit, and try the setup script or manual Keycloak setup? Keycloak def has to work or none of this works for you.  Keycloak setup first, then edit the .env on the OpenRMF stack, and then spin that one up.

**Comment by crl0901** [comment]
Sorry, I haven't had time to work on this.  I will try to get to it later today.

**Comment by crl0901** [comment]
Ok, so I have two containers, keycloak_keycloak_1 and keycloak_postgres_1. I brought both of them down.  I tried removing the postgres docker volume but it said it was still in use even though both containers were stopped, so I force removed it.  I bring both keycloak containers back up.  keycloak_keycloak_1 goes into a restart loop.  The docker logs for the container say it can't connect to the database.  I also tried removing everything and re-running the keycloak script to recreate the containers, but I'm still getting that SSL message.

**Comment by Cingulara** [comment]
If you removed the postgres volume you need to setup Keycloak up all over again. I am not sure why you removed the database volume. For OpenRMF OSS the Keycloak piece is in a separate docker-compose stack. If you stop and then restart that you should get to at least a default Keycloak instance on port 9001 or whatever port you are running it in after you wait a few minutes for the Java engine and initial database setup of Keycloak to work. 

If you deleted the database saved data, you have to setup Keycloak to work with OpenRMF the initial way first. Then get SSL to work with the info we have documented.

**Comment by Cingulara** [comment]
@crl0901 did you ever get this working? I need to clean up the tickets in here and wanted to get closure.

**Comment by crl0901** [comment]
No, I didn't get it working but you can close this.

**Comment by Cingulara** [comment]
Ok. If this needs to be revisited add a new one and we can possibly get on a video chat and share screen on my end to see how we can get it done.
