### ISSUE TITLE
[BUG] OpenRMF produces inaccurate "NAF" (Not a finding) counts. 

### ISSUE THREAD

**Issue by JDoofenschmirtz** [Cingulara/openrmf-docs#213]
**Describe the bug**
OpenRMF produces inaccurate "NAF" (Not a finding) counts.

**To Reproduce**
1. Within OpenRMF, go to Upload -> Choose Files (Your RHEL 6 ckl) -> Upload and Save
2. Click on the system you uploaded the ckl to and scroll down to the Checklist section
3. Note the number in the NAF column (mine was 135)
4. Open the same ckl file in STIGViewer and note the number next to "Not a Finding:" (mine was 227)

**Expected behavior**
The NAF count in OpenRMF should match the "Not a Finding:" count in STIGViewer

**Screenshots**
![image](https://user-images.githubusercontent.com/77696676/105097464-9eb16a00-5a76-11eb-9125-c4e030cc4f05.png)
![image](https://user-images.githubusercontent.com/77696676/105097542-c56fa080-5a76-11eb-8163-ac58aa20286f.png)

**Desktop (please complete the following information):**
 - Chrome 87 running on Windows 10
 - OpenRMF Version 1.3.1 running on CentOS 7.9
 - Using "REL 6 STIG-V1-R23 dated 26 Jul 2019" checklist file (created by STIGViewer 2.9.1).
 - Also noticed the same issue in "Splunk Enterprise 7.x STIG-V1-R0.1 dated 13 Jan 2020" (created by STIGViewer 2.9.1).

**Additional context**
I attempted the following workarounds to fix the inaccurate counts:
1. Upgrading to the 2020 version of the REL 6 STIG using OpenRMF
2. Splitting the REL 6 STIG file into two ckl files (the two files still added up to 135 NAF within OpenRMF)
3. Removing excess text to shrink the REL 6 STIG file size (the file was 1.2MB, so I thought perhaps it was a file size issue)
4. Counted the number of times NotAFinding appeared in the raw text of the REL 6 STIG ckl file and it was 227 (verifying that STIGViewer was accurate)

None of the workarounds were successful.

**Comment by Cingulara** [comment]
I will have to load the dev stack on this locally and step through it. Give me this weekend as I have too many other things going on now taking my time.

@JDoofenschmirtz Is this RHEL 6 one the only one doing this? Do you notice this with any others or just this one? That will help me narrow down if there is a problem in the code parsing the checklists. I have not run into this issue, but I also have not used the RHEL 6 checklist. I have used loads of other ones, including the ASD and the Windows family, REL 7.x, IBM z/OS, McAfee, databases, even some SRRGs. So I want to see if there is something specific on RHEL6 if you have only seen it on that one.

**Comment by Cingulara** [comment]
Excellent find @JDoofenschmirtz this line 113 has an = instead of a + sign. I need to fix and push out an update along with Template updates this weekend. I tested this locally, and I just re-uploaded that checklist and it corrected the issues.

https://github.com/Cingulara/openrmf-msg-score/blob/b8267a4ef21d5d5fcac69164e38ec7bfe9b40167/src/Classes/ScoringEngine.cs#L113 

When I have the fix out there I will let you know.

**Comment by Cingulara** [comment]
This fix is now in the master branch and fixed @JDoofenschmirtz. You can pull down the latest code in the Release area and get the full update. https://github.com/Cingulara/openrmf-docs/releases/tag/1.3.2

Alternatively, you can shut down the OpenRMF stack only (leave Keycloak alone), and just copy the https://raw.githubusercontent.com/Cingulara/openrmf-docs/master/scripts/docker-compose.yml file contents over top of yours. Then run the "start" script again. It will pull the latest web container (version update), template container (newest public DISA STIG templates), and the container with the fix on the score.
