### ISSUE TITLE
[FEATURE] Allow Keycloak to use client-id and client-secret for API Access

### ISSUE THREAD

**Issue by rsf123** [Cingulara/openrmf-docs#246]
**Is your feature request related to a problem? Please describe.**
New feature request - ability to access API's using third party capabilities by obtaining a JWT using client-ID and client-secret as opposed to using a username/password

**Describe the solution you'd like**
Currently, the openrmf realm is set up to use the "public" access type which allows presentation of a client-id along with a username/password.   To eliminate the need to encode usernames/passwords in API calls from third party capabilities, it would be great if the openrmf realm could support clients with the "confidential" access-type, which allows presentation of a client-id along with a client-secret for "service account" type access.

**Describe alternatives you've considered**
Currently using username/password

**Additional context**
We are attempting to automate the upload of content from some of our tools into OpenRMF without having the use the UI and accessing the Upload API directly.  We haven't had much luck trying to set up a client using the "confidential" access type in order to support a "service account" style access.

**Comment by Cingulara** [comment]
We are working on this in the summer of 2021 actually. We will be adding a way to setup external APIs and front with something like Kong API GW for rate limiting/CORS/ACL/security/etc. to front them as well. This will allow automating upload of SCAP XCCDF Results, CKL, or a .nessus file easily. 

This work coincides with a similar effort on the OpenRMF Professional 2.x side of the house. https://www.soteriasoft.com/ has info on that. So we will use what we learn on security from that to help implement this in the separate OSS codebase as well.

I believe this is what you are asking for and referring to.

**Comment by rsf123** [comment]
That's exactly what we're looking for.  In the meantime, we did get a token based auth method set up with the Keycloak server, and can get the access tokens back.  We're playing with a way to streamline the whole process and Kong API GW was something we were looking at...  Be great when this is a native part of the application

**Comment by Cingulara** [comment]
An external API feature for pushing SCAP XML, CKL, or .nessus files is coming in the OpenRMF Professional v2.6 due out in the next week or less. https://www.soteriasoft.com/products/openrmf-professional.html is the URL for that. And it uses Vault to store the information.

I will post here when it is out and you can sign up to get a 30-day evaluation of it to test out the API to automate even more of this.

**Comment by thethirstyturtle** [comment]
Is the API open on the OSS version? I've attempted to query the read API, but keep getting a 401 Unauthorized error.

**Comment by Cingulara** [comment]
https://dale-bingham-cingulara.medium.com/openrmf-professional-v2-6-released-api-included-1831e8ff7a4

v2.6 of the Professional version has the API now in it FYI

**Comment by DaleBinghamSoteriaSoft** [comment]
Leaving in the Professional version for now.
