### ISSUE TITLE
[BUG] adding HTML characters like < and > need to be encoded/decoded correctly for editing and viewing

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#253]
**Describe the bug**
One some of the VULN items the fix text has HTML or XML and that is hidden. We need to capture the data, encode, POST/PUT, decode and save. 

**To Reproduce**
1. Go to .NET Framework
2. view the 225230 VULN text
3. it is missing the configuration data to use
4. it also is not formatted for line breaks correct as this is HTML

**Expected behavior**
Need to fix the formatting of \n to <br /> as well as other HTML characters to encode/decode on the front end and backend.

**Screenshots**
![image](https://user-images.githubusercontent.com/46137145/136376852-83c9bca2-ee5b-4d47-babe-f2aec09bc7d6.png)

**Additional context**
n/a

**Comment by DaleBinghamSoteriaSoft** [comment]
Fixing in Template and Artifact/Checklist
