### ISSUE TITLE
[BUG] When uploading a SCAP XML file to update a checklist, it copies over all VULNs and all information, not just PASS/FAIL and Finding Details

### ISSUE THREAD

**Issue by DaleBinghamSoteriaSoft** [Cingulara/openrmf-docs#262]
**Describe the bug**
When you are uploading a SCAP XML file to **update** a checklist (not new), it copies over all VULNs and all information, not just PASS/FAIL and Finding Details. 

**To Reproduce**

1. add a SCAP to create a new checklist entry
2. update items that are Not Reviewed and not pass/fail that SCAP does not check
3. add comments to those that the SCAP marked as Not a Finding or Open as well
3. save that checklist
4. update a newer SCAP for the same checklist type and hostname
5. notice all VULN info is updated, including those not scanned as Not Reviewed, and any finding details, comments, etc. are lost!

**Expected behavior**
It only updates PASS/FAIL information for Finding Details and Status. Comments, Severity Override info should be left as-is in the checklist.

**Additional context**
Impacts all versions up to the latest 1.7 so has to be a patch.

**Comment by Cingulara** [comment]
Fixed in the latest version released today
