### ISSUE TITLE
[FEATURE] Host Name search in the System Checklist Filter should not be case-sensitive

### ISSUE THREAD

**Issue by phopfner-dli** [Cingulara/openrmf-docs#268]
**Is your feature request related to a problem? Please describe.**
This is written against v1.7.2 of the Open-Source product.  On the "System Package Information" page, under the "Checklist Filter" there is a "Host Name" search field.  That search field appears to be case-sensitive.

**Describe the solution you'd like**
A non-case sensitive search field

**Describe alternatives you've considered**
None

**Additional context**
Easy to repro

**Comment by DaleBinghamSoteriaSoft** [comment]
Verified and working on this now @phopfner-dli sorry this took so long.

**Comment by DaleBinghamSoteriaSoft** [comment]
This got lost in the shuffle of other updates. We just audited all the "todo's" and saw this. It is now fixed in the upcoming v1.9 release. 

![image](https://user-images.githubusercontent.com/92731210/223716091-2b87201b-1855-48e9-a055-5c4d45529a62.png)
