### ISSUE TITLE
[FEATURE] Update the POAM export to more match eMASS formats for DoD folks

### ISSUE THREAD

**Issue by DaleBinghamSoteriaSoft** [Cingulara/openrmf-docs#272]
**Is your feature request related to a problem? Please describe.**
The POAM in XLSX is not 100% compatible with eMASS format so we should update that. 

**Describe the solution you'd like**
A better format matching eMASS POAM format. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Cingulara** [comment]
Need to add in the merged cells for borders and such to work well

```
MergeCells mergeCells = new MergeCells();
mergeCells.Append(new MergeCell() { Reference = new StringValue("A1:F1") });
mergeCells.Append(new MergeCell() { Reference = new StringValue("A2:F2") });

// save the merged cells
worksheetPart.Worksheet.InsertAfter(mergeCells, worksheetPart.Worksheet.Elements<SheetData>().First());

// Save the new worksheet.
workbookpart.Workbook.Save();
```
