### ISSUE TITLE
[FEATURE] Use the AJAX data tables routines to quicken the tables where possible

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#286]
**Is your feature request related to a problem? Please describe.**
There is a way to call the tables as an AJAX source and then format the data in the table definition. It quickens the load of data. 

**Describe the solution you'd like**
See where we are listing a lot of data such as a checklist listing or template listing and update the datatable to use Ajax src versus data table row.add() type of routine. 

**Describe alternatives you've considered**
n/a

**Additional context**
[DataTables AJAX calls](https://datatables.net/reference/option/ajax)](https://datatables.net/reference/option/ajax)

**Comment by DaleBinghamSoteriaSoft** [comment]
The Score API is called dynamically so cannot do it as we do in PRO where that is combined...for checklists and templates.

**Comment by DaleBinghamSoteriaSoft** [comment]
Host Vulnerability report and Controls report can use this. 

And Host Vuln report we should do a PARTIAL match
