### ISSUE TITLE
[BUG] Microsoft Defender Antivirus does not detect the upgrade

### ISSUE THREAD

**Issue by Cingulara** [Cingulara/openrmf-docs#299]
**Describe the bug**
The STIG CKL for v2 r3 "Windows Defender Antivirus Security Technical Implementation Guide" does not detect there is an upgrade. The newer STIG title of course changed by DISA to "Microsoft Defender Antivirus Security Technical Implementation Guide
" so we need to update the search to a Regex and trim words.

**To Reproduce**
1. Go to a checklist for Defender v 2 r 3 or earlier
2. Notice there is not an upgrade notification

**Expected behavior**
The upgrade shows up. 

Need to check the Template MSG and Template API call on "is there an update" to make sure the matching, regex, and DISA's moving/removing of Microsoft and Windows is accounted for...

**Screenshots**
Older Version:
![image](https://user-images.githubusercontent.com/46137145/204138511-995c17ae-67f6-4883-927e-c6dd7bb2bbfd.png)

Newer Template:
![image](https://user-images.githubusercontent.com/46137145/204138525-18565a87-66b8-43ad-8440-52cca39da311.png)

**Comment by DaleBinghamSoteriaSoft** [comment]
This is fixed. Had to do with title and type changes.
