### ISSUE TITLE
[BUG] Matching on Some scans not working correctly

### ISSUE THREAD

**Issue by DaleBinghamSoteriaSoft** [Cingulara/openrmf-docs#313]
**Describe the bug**
There are certain SCAP scan results that do not match up to the right template. The ones we know of are below:
* CISCO NX and other 2-letter abbreviation STIG types
* Windows 2012
* Windows 2022 sometimes
* Windows 2016 sometimes
* DISA SCC with enhanced results

**To Reproduce**
1. Load the scan
2. Upload it to OpenRMF OSS
3. Fails to match to the template to fill in

**Expected behavior**
It matches, fills it out, and adds to the listing

**Additional context**
Deals with DISA and others changing their types and the matching sequence for our side.

**Comment by Cingulara** [comment]
Fix for matching the titles that DISA keeps changing back and forth...

Configuration Management anyone?
