### ISSUE TITLE
[FEATURE] Update a Test plan based on the Nessus scan file

### ISSUE THREAD

**Issue by redxking** [Cingulara/openrmf-docs#49]
Add the ability to upload a test plan and auto fill the required fields with the relevent information from the .nessus scan file.

**Comment by Cingulara** [comment]
Version 0.10 right now we are working to upload Nessus scan and update checklists so will look at this as well. @degthat8412

**Comment by Cingulara** [comment]
Nessus scans are across all servers within a "System" in OpenRMF view. We are allowing an update of a Nessus scan in version 0.10.

In version 0.12 in the https://github.com/users/Cingulara/projects/7 project layout we are doing the reports such as Risk Assessment Report (RAR), the POA&M on open items and this Test Plan across a system.  https://github.com/Cingulara/openrmf-web/issues/98 has the UI pieces and outline of it. Based on breaking this down further the other pieces of this application (API, msg, database) will have their tickets added to work against and put into version 0.12.

**Comment by redxking** [comment]
Do you have an email address we can exchange? I have a team doing a similar project for our people in DOD. 

Angelis Pseftis
Senior Security Engineer
Cell: 910-751-0727
Angelis.pseftis@icloud.com
Nick.pseftis@gmail.com

**Comment by Cingulara** [comment]
@redxking I sent you an email from my dale.bingham@cingulara.com email earlier.
