### ISSUE TITLE
[FEATURE] Put the full CCI with description listed in the template in the web viewer for checklists

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-docs#77]
**Describe the bug**
The CCI listed in the viewer shows a GUID, and a CCI-number.  Comparing the checklist, some data is not showing in OpenRMF

**To Reproduce**
1. Go to a checklist and open a vulnerability ID.
2.  Scroll down to the CCI-ID section
4. See error:  A GUID and a CCI number exitst.  There is important information missing compared to STIG viewer.

**Expected behavior**
Display the additional NIST data.

**Screenshots**
See OpenRMF view compared to STIG viewer

Using development version of OpenRMF (10.9.1)
![CCI-View-OpenRMF-Viewer](https://user-images.githubusercontent.com/57148328/72252120-08717b00-35bc-11ea-94b0-34d93b92dfff.PNG)
![CCI-View-STIG-Viewer](https://user-images.githubusercontent.com/57148328/72252140-0c9d9880-35bc-11ea-9cdd-20ddb3f081b5.PNG)

**Comment by Cingulara** [comment]
Yes, that would require another lookup from the way they store all their data. I can add that to a backlog to use as well. We have the data, just in a different part. It would not be hard to add that in.

**Comment by Cingulara** [comment]
Need to make some kind of a call, passing all CCI's and get back all NIST information on Controls.

**Comment by Cingulara** [comment]
Java Viewer has it like this:  

![image](https://user-images.githubusercontent.com/46137145/77213239-8718f600-6ae0-11ea-87b1-5dc73d1e0d15.png)

**Comment by Cingulara** [comment]
OpenRMF:  We need to put the CCI title and all relevant NIST references against that CCI. And the References section should go at the bottom of the screen versus in the middle as it is now. 

![image](https://user-images.githubusercontent.com/46137145/77213284-add72c80-6ae0-11ea-9bd0-243eb46f233b.png)

**Comment by Cingulara** [comment]
The compliance listing shows below how this data is found. It shows the definition/title as well as the references within it. 

We need to expose an API within the Compliance area and show how the CCI matches the NIST data correctly. This is a new API endpoint and would call the Request/Reply msg with the data by passing in the CCI-xxxxxx number and getting back records accordingly with the Definition and 1 or more references.

```
<cci_item id="CCI-001453">
			<status>draft</status>
			<publishdate>2009-09-29</publishdate>
			<contributor>DISA FSO</contributor>
			<definition>The information system implements cryptographic mechanisms to protect the integrity of remote access sessions.</definition>
			<type>technical</type>
			<references>
				<reference creator="NIST" title="NIST SP 800-53" version="3" location="http://csrc.nist.gov/publications/PubsSPs.html" index="AC-17 (2)" />
				<reference creator="NIST" title="NIST SP 800-53A" version="1" location="http://csrc.nist.gov/publications/PubsSPs.html" index="AC-17 (2).1" />
				<reference creator="NIST" title="NIST SP 800-53 Revision 4" version="4" location="http://csrc.nist.gov/publications/PubsSPs.html" index="AC-17 (2)" />
			</references>
		</cci_item>
```

**Comment by Cingulara** [comment]
For multiple CCI, group the information

![image](https://user-images.githubusercontent.com/46137145/77228260-70b08000-6b5c-11ea-9429-c172a6f9c6a9.png)
