### ISSUE TITLE
[NEED HELP] Authentication problem with Keycloak

### ISSUE THREAD

**Issue by ahmerjaved22** [Cingulara/openrmf-docs#90]
I followed the instructions to set up keycloak and left all defaults. However when i tried to log in the Openrmf complains about"There is an Authentication problem. Please logout and log back in. And have the application administrator verify your API's authentication settings.".. Any ideas what could cause this?

**Comment by Cingulara** [comment]
First thought is where you are running the `./start.sh` or `./start.cmd` check the .env file. If you used the GH repo to clone or you pulled down the release ZIP file, there is a .env file in there with two lines like below. The http://xxxxxxxx should point to the Keycloak. I use the keycloak setup in the https://github.com/Cingulara/openrmf-docs/tree/master/scripts/keycloak area and run it on port 9001. 

JWT-AUTHORITY=http://192.168.13.28:9001/auth/realms/openrmf
JWT-CLIENT=openrmf

I believe there is a bug at https://github.com/Cingulara/openrmf-web/issues/156 for keycloak needing to be hardcoded to 9001 right now also in the JS files. That is still to be fixed.  If you need to work around that, you also could change the .env and then mount a file into the openrmf-web container at /usr/share/nginx/html/js/auth.js to mimic https://github.com/Cingulara/openrmf-web/blob/master/js/auth.js until that gets fixed.

Let me know if that does it for you. You may be able to see an "unauthenticated" response in your browser if you use the "developer tools" in Chrome, FF, or IE from the calling API possibly.

**Comment by ahmerjaved22** [comment]
I have the correct IP hard coded in the .env file

**Comment by Cingulara** [comment]
Ok. I get these 401's when I am not doing one of a couple things. I just setup OpenRMF for a demo on a new laptop and it worked w/ the latest information. 

* Does your login you made / registered for have at least a "Reader" role? I put Reader as an auto-assign role for registration so people at least have something. You have to have Reader to hit any API endpoints. 

* make sure the Keycloak has the :8080/* at the end of the Valid URIs
* make sure the web origins is *
* make sure you are not calling OpenRMF, or referencing OpenRMF or calling Keycloak, with "http://localhost" as localhost to a container is itself ( I stumble into that every so often again and again myself)

Questions: 
* Are you allowed to screenshot the client setup of 'openrmf' in Keycloak? 
* and a screenshot of the .env file? 
* Does the OpenRMF page show up after a successful login?

**Comment by ahmerjaved22** [comment]
<img width="795" alt="Screen Shot 2020-02-04 at 4 22 47 PM" src="https://user-images.githubusercontent.com/60660099/73788345-db535b00-476a-11ea-9535-68637ec11034.png">
![Screen Shot 2020-02-04 at 4 23 49 PM](https://user-images.githubusercontent.com/60660099/73788355-e1493c00-476a-11ea-9f1e-ef7a38158161.png)
![Screen Shot 2020-02-04 at 4 20 56 PM](https://user-images.githubusercontent.com/60660099/73788363-e4442c80-476a-11ea-9971-4535263932c6.png)

**Comment by ahmerjaved22** [comment]
![Screen Shot 2020-02-04 at 4 23 49 PM](https://user-images.githubusercontent.com/60660099/73788416-ff16a100-476a-11ea-8dfb-7053dcf1a1e6.png)
<img width="795" alt="Screen Shot 2020-02-04 at 4 22 47 PM" src="https://user-images.githubusercontent.com/60660099/73788425-0342be80-476b-11ea-9048-16b89d1f26cd.png">

**Comment by ahmerjaved22** [comment]
closed by accident.. trying to attach the screen shots

**Comment by ahmerjaved22** [comment]
![Screen Shot 2020-02-04 at 4 23 49 PM](https://user-images.githubusercontent.com/60660099/73788532-2cfbe580-476b-11ea-936e-3279ba1dcaa4.png)

**Comment by ahmerjaved22** [comment]
<img width="795" alt="Screen Shot 2020-02-04 at 4 22 47 PM" src="https://user-images.githubusercontent.com/60660099/73788561-37b67a80-476b-11ea-8cc2-eec85dc25985.png">

**Comment by ahmerjaved22** [comment]
![Screen Shot 2020-02-04 at 4 20 56 PM](https://user-images.githubusercontent.com/60660099/73788584-40a74c00-476b-11ea-9a89-f893797b984b.png)

**Comment by ahmerjaved22** [comment]
first one is what i get once i log in. The system is planned to be airgapped later on.

**Comment by Cingulara** [comment]
The IP in the .env looks wrong to me from here. .96 versus .196. The web UIs have .196. The .env has .96.

If you could, go into the OpenRMF scripts directory, run `./stop.sh` and then fix the .env file. Then run `./start.sh` and log in to see what you get. 

Your Valid URIs (you may not need the root URL if you put the full URI):
![image](https://user-images.githubusercontent.com/46137145/73791358-23c14780-4770-11ea-90c5-a58bb68a30a6.png)

versus 

Your .env from above has 192.168.16.96 in it, not x.x.x.196. 
![image](https://user-images.githubusercontent.com/46137145/73791411-3fc4e900-4770-11ea-93f6-43cc3e85f4c0.png)

**Comment by Cingulara** [comment]
You can go to the :9001 URL, login w/ the "admin" into Keycloak, go to the `openrmf` realm and check the users there to make sure your user account has at least the Reader role (case spelling). You will want the Administrator role really to see everything.

You also can go into your Users -- username account and kill any session you currently have.

**Comment by ahmerjaved22** [comment]
![Screen Shot 2020-02-04 at 5 16 40 PM](https://user-images.githubusercontent.com/60660099/73792391-2c1a8200-4772-11ea-8ffb-986aa399c69c.png)

fixed the IP and still same error

**Comment by ahmerjaved22** [comment]
could this be a stig related setting that causing the issue, I am running the application from a home directory, could this be the issue?

**Comment by Cingulara** [comment]
it should not be. The way you have everything set up looks 100% correct.
You could try bringing it all down and then bringing it all back up just in
case the environment variable didn’t get taken right.

I have had a couple people run this on their computers that are windows as
well as Lenix and MacBook. And it has run on all three. There’s going to be
some small thing that’s out of place. I need to look at your images and
screenshots again to see if it jumps out at me.

If the IP addresses are correct, and you are running on port 9001, there
has to be something with your account rolls or the way the compose file is
brought up and running.

Can you do a screen capture of the role mapping section in keycloak?

-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by Cingulara** [comment]
![image](https://user-images.githubusercontent.com/46137145/73794104-abf61b80-4775-11ea-876d-43e1b711a4a3.png)

**Comment by ahmerjaved22** [comment]
![Screen Shot 2020-02-04 at 5 45 22 PM](https://user-images.githubusercontent.com/60660099/73794316-2a52bd80-4776-11ea-8762-9dcf877845f7.png)

**Comment by Cingulara** [comment]
Did you shut both of the stacks down and then bring them both back up?
Keycloak first and the application itself second ?  Shut all the way down
with the shell or CMD and then bring back up?

I can’t see anything else that’s wrong honestly the APIs are getting 401
errors because Either the APIs aren’t linking to keycloak correctly, your
user doesn’t have the right toles, or some other configuration I can’t see.
And the first two you’ve already shown to be OK.
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by Cingulara** [comment]
@degthat8412 any ideas?

**Comment by degthat8412** [comment]
Going through all of the screens shots and the firs difference I can see for my setup and this one is I do not have a root url on the clients/OpenRMF/Settings.  Also have you tried clear the cache under Realm Settings /Cache?

**Comment by Cingulara** [comment]
Ok. So remove the Root URL, clear cache in the realm, and you could
probably clear browser cache just to be safe. As well as bring everything
all the way down and then everything all the way up as far as the two main
pieces of Keycloak and the actual application.
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by degthat8412** [comment]
Do we know if he is using the latest version of OpenRMF?  The screen showing the api's and containers spinning up did not seem complete based on what I have.

**Comment by Cingulara** [comment]
Does not matter for the problem here
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by ahmerjaved22** [comment]
I deleted everything and started from scratch, I went through all the steps except for setting the password policy. However I am still getting the same message. I also moved the location the script is being ran from. so instead of /home/user1, I am running from /opt/openrmf. I really hope this tool starts to work, really could use it.

**Comment by ahmerjaved22** [comment]
<img width="1369" alt="Screen Shot 2020-02-05 at 2 07 07 PM" src="https://user-images.githubusercontent.com/60660099/73874101-e10b7800-4820-11ea-9a53-8558ad6a4852.png">

**Comment by ahmerjaved22** [comment]
<img width="1665" alt="Screen Shot 2020-02-05 at 2 15 52 PM" src="https://user-images.githubusercontent.com/60660099/73874752-119fe180-4822-11ea-8093-e354a2c541f3.png">

**Comment by ahmerjaved22** [comment]
Second screenshot is from the demo. Both are throwing 404 errors. could this be a bug?

**Comment by Cingulara** [comment]
I am on the demo site, just killed all my cache, logged in, went to the dashboard and the system, checklist, other pages and I never see this problem.  I am looking at the Console window to see if I can find anything. 

What OS are you using? And what browser? I am testing on FF, Chrome, and Safari right now as I do not have a Windows laptop or VM w/ a valid license.

Did you say you are on windows? Using the start.cmd? or a VM? or the "linux on windows" kernel they added? Something else? I cannot duplicate anything you are doing.

**Comment by ahmerjaved22** [comment]
I am using RHEL 7 to source the Openrmf application. I run from then on Mac OSX
<img width="558" alt="Screen Shot 2020-02-05 at 2 20 34 PM" src="https://user-images.githubusercontent.com/60660099/73875197-d9e56980-4822-11ea-94ce-e257c75c893f.png">

**Comment by Cingulara** [comment]
I saw the "/opt/openrmf" link above. The location should not matter as this is all w/in containers. 

You also could run `docker-compose up ` without the -d and have it print the logs out to the screen. Capture all these logs into a TxT file and attach or email dale.bingham@cingulara.com so we could possibly see the output as well. Or use >> into a file to use them all.

**Comment by Cingulara** [comment]
So you are running this on REL 7.x, with docker and docker compose, and then viewing it from a MAC machine on the same network? 

Something is still not right w/ the config for every single API call to fail. 

Is there any way you can put it all on your MAC to see if it is something with the REL 7 setup? I am running out of options here to test w/o physically being there or doing a screenshare over Hangout or something.

**Comment by Cingulara** [comment]
FYI those JS errors of 404 above, those are mapper files and no that is not important. 

I am using Safari on my MAC right now and I can run the Demo site 100% fine.  Can you run the https://demo.openrmf.io/ site correctly?

**Comment by ahmerjaved22** [comment]
yes the demo site works correctly, let me try and set this up on the mac and see if that works. if so then its just a matter of something is locked down on the system that is breaking the application. I assume there is a stig setting somewhere that is disallowing access.

**Comment by Cingulara** [comment]
Is there a way to temporarily disable the firewalld or whatever it is called now on REL7? To see if that is indeed it and that needs some ports to open between the MAC and it? And then once tested, put it back together? I know @degthat8412 and I have had to do that to test certain pieces on a project with REL7 as well as with setting up Pi-hole w/ Pi 3 boards.

Can you run this on REL 7 itself locally with a GUI or is REL 7 setup only with the console login?

**Comment by Cingulara** [comment]
Sorry this is being such a pain. Once we know what it is, I need to document it in the DOCS area referencing whatever we are running into. Sorry you are the guinea pig on this one.

**Comment by ahmerjaved22** [comment]
[root@RHEL7 scripts]# ./start.sh
Creating network "scripts_openrmf" with the default driver
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-d1a8fe0370a3 -j RETURN: iptables: No chain/target/match by that name.
 (exit status 1))

Run http://{ip-address}:8080/ to access OpenRMF

[root@RHEL7 scripts]#

**Comment by ahmerjaved22** [comment]
that is after i turned off the firewall

**Comment by ahmerjaved22** [comment]
I really like the idea and concept of the application you guys are working on. I want to introduce this to my organization as we are building up a system currently and need to work on RMF controls in a short period of time.

**Comment by Cingulara** [comment]
Then you need this tool.  We have to figure this out.

Dave May have some more insights.  See if uuu can get on your MAC and if so
it is something on REL more than likely.
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by Cingulara** [comment]
@ahmerjaved22 

The latest fixes and updates to show version of checklists, nessus filename, etc. are all linked in here. To use, run `stop.sh` to shut down the OpenRMF pieces, then copy the data in here https://raw.githubusercontent.com/Cingulara/openrmf-docs/develop/scripts/docker-compose.yml overtop your current docker-compose you run OpenRMF with, then run `start.sh` and it will pull the latest 5 or 6 image updates and run.

Let's make sure you have the latest as well just to make sure I did not introduce anything odd in my release. Your .env should be good as it is, unless you change IPs. This also has the code to generate a test plan summary XLSX.

This fixes a bug on upload, adds fields to track checklist version and nessus filename, etc.
And you should see the “generate test summary” on the System page.

**Comment by Cingulara** [comment]
you will need to be connected to the internet to pull the latest 0.12 images. 

FYI, I did this on my one laptop just now, then turned off WiFi and plugged it up to a local powered switch connected to nothing. I made a manual IP (no DHCP) and ran the `start.sh` and it worked fine. This is "disconnected" on my MacBook Pro. The 169.x.x.x self IP for Windows does not act the same when my Mac is disconnected. So I plug in a USB-based network cable to a powered switch, nothing else, and it acts like it is good to go "disconnected".

**Comment by ahmerjaved22** [comment]
you will be pleased to know about this. so i have isolated the problem to the firewall. so there is something in the firewall that breaks the application from working. So what I did was ran ./start.sh with firewall on. Then did a systemctl stop firewalld. reloaded the browser that caused the application to work successfully. so the problem relates to a setting on firewall. Any reccomendations on what I should open up?

**Comment by Cingulara** [comment]
the Ports we expose on the docker compose file

9001 for Keycloak
8080 for the web UI
8082-8096 even numbers for APIs
3000 for Grafana

Start with those
-- 
Dale Bingham
CTO and Chief Technology Evangelist
Cingulara
https://www.cingulara.com
410-984-0001

**Comment by ahmerjaved22** [comment]
ok so after opening up those ports on the firewall this now works!, Amazing. I am sorry for any frustration I may have caused unintentionally. Thank you for your support!, I will recommend some ideas I have to you on slack.

**Comment by powertim** [comment]
Hi, I'm having the same issue:
![image](https://user-images.githubusercontent.com/8004432/174068638-ce442c80-7611-414d-b691-0f5c3ad124bb.png)
![image](https://user-images.githubusercontent.com/8004432/174069192-431919c5-6806-4cb7-b53d-ee29f5ef4244.png)
![image](https://user-images.githubusercontent.com/8004432/174069264-3f2a2a28-5b20-491f-b01d-6c8487e9c19b.png)

No firewalld in place, all ports listening and opened (check from my laptop with telnet command).

I just changed the port for Keycloak and adjusted the port in the auth.js file.

All steps followed correctly, still having the 401 error and OpenRMF is unusable.

Thanks for your help!

**Comment by Cingulara** [comment]
@powertim  Keycloak in our OpenRMF OSS is set to port 9001 hard coded. In the Keycloak docker-compose as well as in the auth JS file in the web frontend. Can you go to http://{ipaddress:9001/auth/ and login with the default admin/admin? 

You cannot use "localhost" as this uses containers and localhost = itself. And your .env, the Keycloak URL, and the OpenRMF OSS url all have to be using the same IP address or DNS name to validate the JWT properly. 

I see you are getting 401 Unauthorized, so usually that points to the JWT not being valid or passed in correctly. Please make sure Keycloak is setup as is from the Releases page https://github.com/Cingulara/openrmf-docs/releases and is running and was configured for the "openrmf" client. And then that the .env for the OpenRMF OSS stack points to that via the IP or DNS.

**Comment by DaleBinghamSoteriaSoft** [comment]
@powertim Mike Bosland wrote up a step on HTTPS and stuff that may help here:  https://mikebosland.com/how-to-configure-openrmf-io-to-use-domain-names-and-tls/

**Comment by powertim** [comment]
Hi @Cingulara  & @DaleBinghamSoteriaSoft this is not working at all.
#

> @powertim Keycloak in our OpenRMF OSS is set to port 9001 hard coded. In the Keycloak docker-compose as well as in the auth JS file in the web frontend. Can you go to http://{ipaddress:9001/auth/ and login with the default admin/admin?
> 
Yes this is working! I can login to Keycloack as admin and as rmf-admin for managing openrmf.
I also had to modify file apis.js which was referencing port 9001.
My docker-compose looks like this (no other modifications elsewhere):
```version : '3.8'

services:
### 1 Web Front End Container
  openrmf-web:
    image: cingulara/openrmf-web:1.08.02
    container_name: openrmf-web
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - openrmfapi-scoring
      - openrmfapi-template
      - openrmfapi-read
      - openrmfapi-controls
      - openrmfapi-audit
      - openrmfapi-report
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth.js:/usr/share/nginx/html/js/auth.js:ro
      - ./apis.js:/usr/share/nginx/html/js/apis.js:ro
    networks:
      - openrmf
```

> You cannot use "localhost" as this uses containers and localhost = itself. And your .env, the Keycloak URL, and the OpenRMF OSS url all have to be using the same IP address or DNS name to validate the JWT properly.
> 
I'm always using FQDN of the server everywhere I can (KeyCloak, JWT .env file, nginx.conf)
> I see you are getting 401 Unauthorized, so usually that points to the JWT not being valid or passed in correctly. Please make sure Keycloak is setup as is from the Releases page https://github.com/Cingulara/openrmf-docs/releases and is running and was configured for the "openrmf" client. And then that the .env for the OpenRMF OSS stack points to that via the IP or DNS.
>
all steps were followed using the instructions https://github.com/Cingulara/openrmf-docs/blob/develop/step-by-step.md

I'm still getting 401 error with latest version.
Does API port needs to be opened from client browser or it's just forwarded from openrmf-web container ?

> the Ports we expose on the docker compose file 9001 for Keycloak 8080 for the web UI 8082-8096 even numbers for APIs 3000 for Grafana Start with those -- Dale Bingham CTO and Chief Technology Evangelist Cingulara https://www.cingulara.com 410-984-0001

I'm talking about this.

Thanks for helping me.

**Comment by DaleBinghamSoteriaSoft** [comment]
@powertim did you ever get this fixed? 

That initial image above showing :8084 and other ports should only be happening IF you are running this through code. 

If you are running this from the releases all behind a docker or podman setup, that should not happen. How are you running this?

We are getting ready to put Keycloak under NGINX /auth/ and Grafana under /metrics/ for the OpenRMF OSS as well. But again, this will all be under a container network we run. You don't run individual pieces unless you want to do development. Then it is a little trickier with the nginx.conf and other stuff to map to VSCode type of individual code bases running.

**Comment by DaleBinghamSoteriaSoft** [comment]
This is all updated now with v1.9 so please check the main site https://github.com/Cingulara/openrmf-docs/ as well as the docs off https://www.openrmf.io/ as Keycloak moved under a single `docker-compose.yml` file. And we have setup and HTTPS setup documented well.
