### ISSUE TITLE
Delete selected checklist from system page not working - workaround.

### ISSUE THREAD

**Issue by mtnnomad** [Cingulara/openrmf-docs#96]
When on the System View page and attempting to delete checklists, singularly or in multiples, an error occurs.  Dev tools show a HTTP 400 Bad request error.  
**To Reproduce**
1. Go to a system containing checklists.
2. Select on or more checklists radial button.
3. Press the "delete Selected" button.
4. See error.  returns a 400 error.  

NOTE:  "delete all" function works.
NOTE:  If I select the checklist hyperlink and open it in another page, this delete function works.

**Expected behavior**
Delete the selected checklists.  

**Screenshots**
Working on a disconnected system.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version: Open RMF Dev 12.4

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Cingulara** [comment]
I just verified on the demo site (has the latest) that this is a problem as well. So I will fix this today.

**Comment by Cingulara** [comment]
Fixed in cingulara/openrmf-web:0.12.5
